"""Write the corrected public_chat.py file."""

# Build content as a list of lines
L = []
L.append('"""Phase 6.13 - Public (unauthenticated) chat endpoint service.')
L.append('')
L.append('Mirrors app.services.chat.process_chat_request so that public conversations')
L.append('reuse the same chat boundary, turn/conversation ownership model, bounded')
L.append('history, query rewriting, retrieval, generation, and citation pipeline -')
L.append('EXCEPT:')
L.append('')
L.append('1. user_id is always PUBLIC_USER_ID (a constant, never derived from a JWT).')
L.append('2. Personalization is never loaded (no current_user -> no student context).')
L.append('3. institution_id is accepted for forward-compatibility but does not')
L.append('   participate in any tenant-scoped authorization check.')
L.append('"""')
L.append('')
L.append('from __future__ import annotations')
L.append('')
L.append('import re')
L.append('import threading')
L.append('import time')
L.append('from uuid import UUID')
L.append('')
L.append('from app.config import settings')
L.append('from app.core.errors import AppError')
L.append('from app.core.security import PUBLIC_USER_ID')
L.append('from app.db.supabase import get_admin_client')
L.append('from app.repositories.ai_response import create_ai_response')
L.append('from app.repositories.conversation import (')
L.append('    create_conversation,')
L.append('    get_conversation,')
L.append('    update_conversation_timestamp,')
L.append(')')
L.append('from app.repositories.message import create_message, get_next_message_sequence')
L.append('from app.repositories.message_citation import create_message_citations')
L.append('from app.repositories.retrieval_operation import (')
L.append('    create_retrieval_operation,')
L.append('    create_retrieved_chunks,')
L.append(')')
L.append('from app.schemas.citation import (')
L.append('    MessageCitationCreate,')
L.append('    RetrievedChunkCreate,')
L.append('    RetrievalOperationCreate,')
L.append(')')
L.append('from app.schemas.chat import ChatRequest, ChatResponse')
L.append('from app.schemas.chat_response import ChatUsage, StructuredSource')
L.append('from app.schemas.conversation import (')
L.append('    AIResponseCreate,')
L.append('    ConversationCreate,')
L.append('    MessageCreate,')
L.append(')')
L.append('from app.schemas.generation import (')
L.append('    AIRequest,')
L.append('    ConversationTurn,')
L.append('    RetrievalScope,')
L.append('    RetrievedChunk,')
L.append('    SourceReference,')
L.append(')')
L.append('from app.schemas.retrieval import RetrievalRequest, RetrievalResponse, RetrievalResult')
L.append('from app.schemas.session import SessionContext')
L.append('from app.services.context import assemble_context')
L.append('from app.services.conversation_history import get_conversation_messages')
L.append('from app.services.generation import AIGenerationService')
L.append('from app.services.generation_provider import GenerationProvider')
L.append('from app.services.query_rewriting import rewrite_query')
L.append('from app.services.retrieval import retrieve')
L.append('')
L.append('__all__ = ["process_chat_request"]')
L.append('')

import os
os.chdir('F:\\Git Project\\CollegeAIChatbot\\backend')
content = '\n'.join(L)
with open('app/services/public_chat.py', 'w') as f:
    f.write(content)
print('Imports written')
